name: Auto Assign Author

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  auto-assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@540688a3f286ff2625e705bb6b5ed6f9def14754 #https://github.com/toshimaru/auto-author-assign