name: Deploy Docker Image in Prod

on:
  release:
    types: [released]
  push:
    branches:
      - 'release-v**'
      - 'release/v**'

jobs:
  build-and-deploy-to-acr:
    runs-on: ubuntu-latest
    environment:
      name: prod
    name: Build and Deploy API Image to ACR
    steps:     
      - uses: actions/checkout@v3
           
      - run: |
          echo ${{ github.ref_name }}

      - name: Fetch release version from automated release tag
        if: ${{ github.event_name }} == 'release'
        run: |
          echo "git fetch --prune --unshallow --tags"
          echo "ENVIRONMENT_VERSION=v$(git describe --abbrev=0 --tags | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV;
      
      - name: Fetch release version from manual release branch push
        if: ${{ github.event_name }} == 'push'
        run: |
          echo "ENVIRONMENT_VERSION=v$(git branch --show-current | tr -d 'release/-')" >> $GITHUB_ENV;
      
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'