name: Deploy Docker Image in Prod

on: 
  workflow_dispatch:
    branches:
      - "release-**"
      - "release/**"
    inputs:
      version:
        description: 'The version to deploy from the release branch'
        required: true
      confirmation-for-production:
        description: 'Confirmation message for user'
        required: true
        type: boolean

jobs:
  build-and-deploy-to-acr:
    runs-on: ubuntu-latest
    environment:
      name: prod
    name: Build and Deploy UI Code
    steps:
      - name: Verify if correct version number has been provided in inputs
        run: |
          "${{ github.event.inputs.version }}" == $("${{ github.ref_name }}" | tr -d "release/-")
        continue-on-error: false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.version }}'

      - name: Set DD RUM Version
        run: |
          echo "REACT_APP_DD_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV;

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

