name: Deploy Docker Image in Prod

on:
  workflow_run:
    workflows: ["Create release branch for Prod"]
    types: [completed]
  push:
    branches:
      - 'release-v**'
      - 'release/v**'

jobs:
  build-and-deploy-to-acr:
    runs-on: ubuntu-latest
    environment:
      name: prod
    name: Build and Deploy UI Code
    steps:
      - uses: actions/checkout@v3

      - name: Fetch release version from release name
        run: |
          echo "ENVIRONMENT_VERSION=${{ github.ref_name }}" | tr -d 'release/-' >> $GITHUB_ENV;

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

