name: Deploy Docker Image in Prod

on: 
  workflow_dispatch:
    branches:
      - "release-**"
      - "release/**"
    inputs:
      confirmation-message:
        description: 'Are you sure you want to deploy to production'
        required: true
        type: boolean

jobs:
  build-and-deploy-to-acr:
    runs-on: ubuntu-latest
    environment:
      name: prod
    name: Build and Deploy UI Code
    if: inputs.confirmation-message == true
    steps:
      - name: Get Version Number from release Branch
        run: |
          echo "ENVIRONMENT_VERSION=${{ github.ref_name }}" | tr -d 'release/-' >> $GITHUB_ENV;

      - name: Verify if correct version number has been released
        run: |
          curl -H "Accept: application/vnd.github.v3+json"  -H "Authorization: token ${{ github.token }}" "${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/${{ env.ENVIRONMENT_VERSION }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.ENVIRONMENT_VERSION }}

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

