name: DEV Web Deployment

env:
  NODE_VERSION: '16.x'
  REACT_APP_DD_CLIENT_TOKEN: ${{ secrets.REACT_APP_DD_CLIENT_TOKEN }}
  REACT_APP_DD_ENV: ${{ secrets.REACT_APP_DD_ENV }}
  REACT_APP_DD_CLIENT_APP_ID: ${{ secrets.REACT_APP_DD_CLIENT_APP_ID }}
  
on:
  workflow_run:
    workflows: ["Create Pre-Release"]
    types: [completed]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    name: Build and Deploy Job
    steps:
      - name: Fetch release version from input
        if: inputs.version != null
        run: |
          echo "ENVIRONMENT_VERSION=${{ inputs.version }}" >> $GITHUB_ENV; 

      - name: Checkout repo for specific version given as an input
        if: inputs.version != null
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.version }}'       

      - name: Checkout repo if version is not given as an input
        if: inputs.version == null
        uses: actions/checkout@v3

      - name: Fetch release version from tags
        if: inputs.version == null
        run: |
          echo "git fetch --prune --unshallow --tags"
          echo "ENVIRONMENT_VERSION=v$(git describe --abbrev=0 --tags | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV;
            
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          type: "latest"
        continue-on-error: true

      - name: Set DD RUM Version
        if: inputs.version == null
        run: |
          echo "REACT_APP_DD_VERSION=${{ steps.node_release.outputs.release }}" | tr -d v >> $GITHUB_ENV;
        continue-on-error: true

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: 'Install packages'
        run: |
          yarn install --frozen-lockfile

      - name: 'Build web app'
        run: |
          yarn run build

      - name: 'Upload sourcemap to datadog'
        env:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
        run: |
          yarn global add @datadog/datadog-ci
          datadog-ci sourcemaps upload ./build/static/js \
            --service=rum-testing-features \
            --release-version=${{ env.REACT_APP_DD_VERSION }} \
            --minified-path-prefix=http://localhost:3000/static/js
        continue-on-error: true
