name: Create Pre-Release

on:
  push:
    branches:
      - master
      - '**-hotfix'
      - 'hotfix/**'
      - 'pre-release-**'
    paths-ignore:
      - '.github/workflows/updateIPLists.yml'

jobs:
  github-release:
    uses: './.github/workflows/github-release.yml'
    with:
      is_pre_release: true
