name: Create Prod Release Branch

on:
  release:
    types: [released]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    name: Creates Release branch From Latest Released tag
    outputs:
      branch_name: release-${{ steps.create_branch.outputs.release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch release version from tags
        run: |
          echo "git fetch --prune --unshallow --tags"
          echo "RELEASE_VERSION=v$(git describe --abbrev=0 --tags | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV;

      - name: create release branch
        id: create_branch
        run: |
          git checkout -b release-${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }}
          git push --set-upstream origin release-${{ env.RELEASE_VERSION }}
          echo "::set-output name=release_version::${{ env.RELEASE_VERSION }}"

  deploy-from-release-branch:
    runs-on: ubuntu-latest
    name: Deploys to Production from Release Branch
    needs: create-release-branch
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-release-branch.outputs.branch_name }}

      - name: Deploy Release from release branch
        uses: './.github/workflows/deploy-prod-testing.yml'
        with:
          confirmation-message: true
          



          
          