name: Create Prod Release Branch

on:
  release:
    types: [released]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    name: Creates Release branch From Latest Released tag
    steps:
      - uses: actions/checkout@v3

      - name: Fetch release version from tags
        run: |
          echo "git fetch --prune --unshallow --tags"
          echo "RELEASE_VERSION=v$(git describe --abbrev=0 --tags | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV;

      - name: create release branch
        id: create_branch
        run: |
          git checkout -b release-${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }}
          git push --set-upstream origin release-${{ env.RELEASE_VERSION }}
          

          



          
          