name: Create release branch for Prod

on:
  release:
    types: [released]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    name: Creates Release branch From Latest Released tag
    steps:
      - uses: actions/checkout@v3

      - name: Fetch release version from tags
        run: |
          echo "git fetch --prune --unshallow --tags"
          echo "RELEASE_VERSION=v$(git describe --abbrev=0 --tags | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')" >> $GITHUB_ENV;

      - name: create release branch
        run: |
          git checkout -b release-${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }}
      
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: push commit to release branch
        run: |
          git commit --allow-empty -m "Release branch ${{ env.RELEASE_VERSION }} created" 
          git push origin release-${{ env.RELEASE_VERSION }}