name: Update Imperva WAF Bypass IPs

on:
  workflow_dispatch:    

jobs:
  checkIps:
    name: Check IPs
    runs-on: ubuntu-latest
    steps:
      - run: echo "$ls"
      - name: Get current networking file
        id: networkingFile
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "./package.json"

      - id: newAllowlistedIpList
        run: |
          response=$(curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips)
          echo $response | jq '.ipRanges'
          
      - id: currentAllowlistedIpList
        run: |
          response=${{ steps.networkingFile.outputs.networking.allowedIpRanges }}
          echo $response | jq '.'
          
      
      - id: equalityOfLists
        run: |
          echo [ "${{ steps.currentAllowlistedIpList.outputs }}" = "${{ steps.newAllowlistedIpList.outputs }}" ]; echo "$?" 