name: Update Imperva WAF Bypass IPs

on:
  push:
    paths:
      - '.github/workflows/updateIPLists.yml'
  workflow_dispatch:   

jobs:
  checkIps:
    name: Check IPs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current networking file
        id: networkingFile
        uses: RadovanPelka/github-action-json@v1.0.1
        with:
          path: "staticwebapp.cofig.json"

      - id: currentAllowlistedIpList
        run: |
          response=${{ steps.networkingFile.outputs.networking.allowedIpRanges }}
          echo $response

      - id: newAllowlistedIpList
        run: |
          response=$(curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips)
          echo $response | jq '.ipRanges'
                          
      - id: equalityOfLists
        run: |
          echo [ "${{ steps.currentAllowlistedIpList.outputs }}" = "${{ steps.newAllowlistedIpList.outputs }}" ]; echo "$?" 