name: Update Imperva WAF Bypass IPs

on:
  push:
    paths:
      - '.github/workflows/updateIPLists.yml'
  workflow_dispatch:   

jobs:
  checkIps:
    name: Check IPs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read JSON and extract array
        id: extract
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const inputFilePath = path.resolve(process.env.INPUT_FILE_PATH);
            const keyToExtract = process.env.INPUT_KEY;
            const data = JSON.parse(fs.readFileSync(inputFilePath, 'utf8'));

            // Handle nested keys
            const keys = keyToExtract.split('.');
            let extractedArray = data;
            for (let i = 0; i < keys.length; i++) {
              extractedArray = extractedArray[keys[i]];
            }
            
            console.log(`Extracted array: ${JSON.stringify(extractedArray)}`);
            core.setOutput('extractedArray', extractedArray);

        env:
          INPUT_FILE_PATH: staticwebapp.cofig.json
          INPUT_KEY: networking.allowedIpRanges

      - name: Use extracted array
        run: echo "Extracted array is ${{ steps.extract.outputs.extractedArray }}"

      - name: Fetch new Imperva IPs
        id: newAllowlistedIpList
        run: |
          new_array=$(curl -s --data "resp_format=json" https://my.imperva.com/api/integration/v1/ips | jq '.ipRanges')
          echo "::set-output name=newAllowlistedIpList::$new_array"
                          
      - name: Compare arrays
        id: compare
        uses: actions/github-script@v4
        with:
          script: |
            const oldArray = JSON.parse(process.env.OLD_ARRAY);
            const newArray = JSON.parse(process.env.NEW_ARRAY);

            if (JSON.stringify(oldArray) === JSON.stringify(newArray)) {
              console.log("Arrays are equal");
            } else {
              console.log("Arrays are not equal");
              console.log(`Old array: ${JSON.stringify(oldArray)}`);
              console.log(`New array: ${JSON.stringify(newArray)}`);
              core.setFailed("Arrays are not equal");
            }

        env:
          OLD_ARRAY: ${{ steps.extract.outputs.extractedArray }}
          NEW_ARRAY: ${{ steps.newAllowlistedIpList.outputs.newArray }}